import { Author, Book, Genre } from "@prisma/client";

export type Filter = 'genre' | 'search';

export const Genres = {
    biography: 'Biography',
    comics: 'Comics',
    culinary: 'Culinary',
    fantasy: 'Fantasy',
    fiction: 'Fiction',
    history: 'History',
    horror: 'Horror',
    music: 'Music',
    phsychology: 'Psychology',
    romance: 'Romance',
    science: 'Science',
    sport: 'Sport',
    thriller: 'Thriller'
} as const;

export const Sorting = {
    trending: 'Trending',
    latest: 'Latest',
    earliest: 'Earliest',
    highestRated: 'Highest rated',
    lowestRated: 'Lowest rated'
} as const;

export const BookTypes = {
    paperback: 'Paperback',
    hardcover: 'Hardcover',
    ebook: 'eBook'
} as const;

export type BaseBook = Book & {
    genre: Genre;
    author: Author;
    readers: {
        id: string;
    }[];
};

export enum ApiErrors {
    unexpected = 'An unexpected error occured.',
    noSession = 'You are not signed in.',
    noBook = 'No book was found for the given id.',
    noReader = 'No reader was found for the given id.'
}

export const Languages = {
    ab: 'Abkhazian',
    aa: 'Afar',
    af: 'Afrikaans',
    ak: 'Akan',
    sq: 'Albanian',
    am: 'Amharic',
    ar: 'Arabic',
    an: 'Aragonese',
    hy: 'Armenian',
    as: 'Assamese',
    av: 'Avaric',
    ae: 'Avestan',
    ay: 'Aymara',
    az: 'Azerbaijani ',
    bm: 'Bambara',
    ba: 'Bashkir',
    eu: 'Basque',
    be: 'Belarusian',
    bn: 'Bengali',
    bi: 'Bislama',
    bs: 'Bosnian',
    br: 'Breton',
    bg: 'Bulgarian',
    my: 'Burmese',
    ca: 'Catalan',
    ch: 'Chamorro',
    ce: 'Chechen',
    ny: 'Chichewa',
    zh: 'Chinese',
    cu: 'Church Slavonic',
    cv: 'Chuvash',
    kw: 'Cornish',
    co: 'Corsican',
    cr: 'Cree',
    hr: 'Croatian',
    cs: 'Czech',
    da: 'Danish',
    dv: 'Devehi',
    nl: 'Dutch',
    dz: 'Dzongkha',
    en: 'English',
    eo: 'Esperanto',
    et: 'Estonian',
    ee: 'Ewe',
    fo: 'Faroeso',
    fj: 'Fijian',
    fi: 'Finnish',
    fr: 'French',
    fy: 'Western Frisian',
    ff: 'Fulah',
    gd: 'Gaelic',
    gl: 'Galician',
    lg: 'Ganda',
    ka: 'Georgian',
    de: 'German',
    el: 'Greek',
    kl: 'Kalaallisut',
    gn: 'Guarani',
    gu: 'Gujarati',
    ht: 'Haitian',
    ha: 'Hausa',
    he: 'Hebrew',
    hz: 'Herero',
    hi: 'Hindi',
    ho: 'Hiri Motu',
    hu: 'Hungarian',
    is: 'Icelandic',
    io: 'Ido',
    ig: 'Igbo',
    id: 'Indonesian',
    ia: 'Interlingua',
    ie: 'Interlingue',
    iu: 'Inukitut',
    ik: 'Inupiaq',
    ga: 'Irish',
    it: 'Italian',
    jp: 'Japanese',
    jv: 'Javanese',
    kn: 'Kannada',
    kr: 'Kanuri',
    ks: 'Kashmiri',
    kk: 'Kazakh',
    km: 'Central Khmer',
    ki: 'Kikuyu',
    rw: 'Kinyarwanda',
    ky: 'Kirghiz',
    kv: 'Komi',
    kg: 'Kongo',
    ko: 'Korean',
    kj: 'Kuanyama',
    ku: 'Kurdish',
    lo: 'Lao',
    la: 'Latin',
    lv: 'Latvian',
    li: 'Limburgan',
    ln: 'Lingala',
    lt: 'Lithuanian',
    lu: 'Luba-Katanga',
    lb: 'Luxembourgish',
    mk: 'Macedonian',
    mg: 'Malagasy',
    ms: 'Malay',
    ml: 'Malayalam',
    mt: 'Maltese',
    gv: 'Manx',
    mi: 'Maori',
    mr: 'Marathi',
    mh: 'Marshallese',
    mn: 'Mongolian',
    na: 'Nauru',
    nv: 'Navajo',
    nd: 'North Ndebele',
    nr: 'South Ndebele',
    ng: 'Ndonga',
    ne: 'Nepali',
    no: 'Norwegian',
    nb: 'Norwegian Bokmål',
    nn: 'Norwegian Nynorsk',
    ii: 'Sichuan Yi',
    oc: 'Occitan',
    oj: 'Ojibwa',
    or: 'Oriya',
    om: 'Oromo',
    os: 'Ossetian',
    pi: 'Pali',
    ps: 'Pashto',
    fa: 'Persian',
    pl: 'Polish',
    pt: 'Portuguese',
    pa: 'Punjabi',
    qu: 'Quechua',
    ro: 'Romanian',
    rm: 'Romansh',
    rn: 'Rundi',
    ru: 'Russian',
    se: 'Northern Sami',
    sm: 'Samoan',
    sg: 'Sango',
    sa: 'Sanskrit',
    sc: 'Sardinian',
    sr: 'Serbian',
    sn: 'Shona',
    sd: 'Sindhi',
    si: 'Sinhala',
    sk: 'Slovak',
    sl: 'Slovenian',
    so: 'Somali',
    st: 'Southern Sotho',
    es: 'Spanish',
    su: 'Sudanese',
    sw: 'Swahili',
    ss: 'Swati',
    sv: 'Swedish',
    tl: 'Tagalog',
    ty: 'Tahitian',
    tg: 'Tajik',
    ta: 'Tamil',
    tt: 'Tatar',
    te: 'Telugu',
    th: 'Thai',
    bo: 'Tibetan',
    ti: 'Tigrinya',
    to: 'Tonga',
    ts: 'Tsonga',
    tn: 'Tswana',
    tr: 'Turkish',
    tk: 'Turkmen',
    tw: 'Twi',
    ug: 'Uighur',
    uk: 'Ukrainian',
    ur: 'Urdu',
    uz: 'Uzbek',
    ve: 'Venda',
    vi: 'Vietnamese',
    vo: 'Volapük',
    wa: 'Walloon',
    cy: 'Welsh',
    wo: 'Wolof',
    xh: 'Xhosa',
    yi: 'Yiddish',
    yo: 'Yoruba',
    za: 'Zhuang',
    zu: 'Zulu'
};